
classifications = {
    0: 'speed limit 20',
    1: 'speed limit 30',
    2: 'speed limit 50',
    3: 'speed limit 60',
    4: 'speed limit 70',
    5: 'speed limit 80',
    6: 'end of speed limit 80',
    7: 'speed limit 100',
    8: 'speed limit 120',
    9: 'no overtaking',
    10: 'no overtaking by lorries',
    11: 'right of way at the next crossroads',
    12: 'priority road',
    13: 'give way',
    14: 'stop and give way',
    15: 'no vehicles',
    16: 'prohibition of lorries',
    17: 'no entry',
    18: 'general caution',
    19: 'dangerous curve to the left',
    20: 'dangerous curve to the right',
    21: 'double curves, first to left',
    22: 'bumpy road',
    23: 'slippery road',
    24: 'road narrows on the right',
    25: 'roadworks',
    26: 'traffic signals',
    27: 'pedestrians',
    28: 'children crossing',
    29: 'bicycles crossing',
    30: 'road freezes easily',
    31: 'wild animals crossing',
    32: 'end of all limits',
    33: 'turn right ahead',
    34: 'turn left ahead',
    35: 'ahead only',
    36: 'go straight or right',
    37: 'go straight or left',
    38: 'keep right',
    39: 'keep left',
    40: 'roundabout mandatory',
    41: 'end of no overtaking',
    42: 'end of no overtaking by lorries'
}

classifications2 = {
    0: 'bumpy road',
    1: 'speed bump',
    2: 'slippery road',
    3: 'dangerous left curve',
    4: 'dangerous right curve',
    5: 'left curve followed by right curve',
    6: 'right curve followed by left curve',
    7: 'children crossing',
    8: 'bicycle crossing',
    9: 'cattle crossing',
    10: 'construction',
    11: 'traffic lights',
    12: 'railway crossing with gates',
    13: 'caution',
    14: 'road narrows to center',
    15: 'road narrows to right',
    16: 'road narrows to left',
    17: 'priority at next intersection',
    18: 'intersection with priority to the right',
    19: 'give way',
    20: 'narrow passage, give way',
    21: 'stop and give way',
    22: 'no entry',
    23: 'no entry for bicycles',
    24: 'no entry for vehicles with more mass',
    25: 'no entry for lorries',
    26: 'no entry for wider vehicles',
    27: 'no entry for higher vehicle',
    28: 'no entry in both directions',
    29: 'no left turn',
    30: 'no right turn',
    31: 'no overtaking',
    32: 'speed limit 70',
    33: 'reserved for cyclists and pedestrians',
    34: 'go straight',
    35: 'go right',
    36: 'go straight or right',
    37: 'roundabout',
    38: 'cycleway',
    39: 'reserved for cyclists and pedestrians',
    40: 'no parking',
    41: 'no parking or standing still',
    42: 'no parking allowed from 1st day to 15th',
    43: 'no parking allowed from 16th to 31st',
    44: 'narrow passage, right of way',
    45: 'parking',
    46: 'handycap parking',
    47: 'parking for cars',
    48: 'parking for lorries',
    49: 'parking for buses',
    50: 'parking on pavement or verge',
    51: 'residential zone',
    52: 'end of residential zone',
    53: 'one way',
    54: 'no exit',
    55: 'end of road works',
    56: 'pedestrian crossing',
    57: 'bicycle crossing',
    58: 'indicating parking',
    59: 'speed bump',
    60: 'priority road',
    61: 'end of priority road'
}