
classifications = {
    0: 'speed limit 20',
    1: 'speed limit 30',
    2: 'speed limit 50',
    3: 'speed limit 60',
    4: 'speed limit 70',
    5: 'speed limit 80',
    6: 'end of speed limit 80',
    7: 'speed limit 100',
    8: 'speed limit 120',
    9: 'no overtaking',
    10: 'no overtaking by lorries',
    11: 'right of way at the next crossroads',
    12: 'priority road',
    13: 'give way',
    14: 'stop and give way',
    15: 'no vehicles',
    16: 'prohibition of lorries',
    17: 'no entry',
    18: 'general caution',
    19: 'dangerous curve to the left',
    20: 'dangerous curve to the right',
    21: 'double curves, first to left',
    22: 'bumpy road',
    23: 'slippery road',
    24: 'road narrows on the right',
    25: 'roadworks',
    26: 'traffic signals',
    27: 'pedestrians',
    28: 'children crossing',
    29: 'bicycles crossing',
    30: 'road freezes easily',
    31: 'wild animals crossing',
    32: 'end of all limits',
    33: 'turn right ahead',
    34: 'turn left ahead',
    35: 'ahead only',
    36: 'go straight or right',
    37: 'go straight or left',
    38: 'keep right',
    39: 'keep left',
    40: 'roundabout mandatory',
    41: 'end of no overtaking',
    42: 'end of no overtaking by lorries'
}